services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    container_name: db-bot
    restart: always
    environment:
      - POSTGRES_USER=larissa_user
      - POSTGRES_PASSWORD=segurademais
      - POSTGRES_DB=larissa_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U larissa_user -d larissa_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - net-bot
  api:
    image: zolppy/aggregator-api:latest
    container_name: api-bot
    environment:
      - BASE_URL_7AZ=${BASE_URL_7AZ}
      - API_KEY_7AZ=${API_KEY_7AZ}
      - DB_URL=${DB_URL}
      - IXC_HOST=${IXC_HOST}
      - OPA_TOKEN=${OPA_TOKEN}
      - OPA_HOST=${OPA_HOST}
      - MIGRATE_DB_URL=${MIGRATE_DB_URL}
      - IXC_TOKEN=${IXC_TOKEN}
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - net-bot
    volumes:
      - .:/app
      - media:/app/media
volumes:
  pgdata:
    driver: local
  media:
    driver: local
networks:
  net-bot:
    driver: bridge
