services:
    db:
        image: postgres:15
        ports:
            - "5432:5432"
        container_name: larissa_postgres
        restart: always
        environment:
            - POSTGRES_USER=larissa_user
            - POSTGRES_PASSWORD=segurademais
            - POSTGRES_DB=larissa_db
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U larissa_user -d larissa_db"]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - larissa_net

    api:
        container_name: larissa_api
        env_file:
            - .env
        build: .
        ports:
            - 8000:8000
        depends_on:
            - db
        networks:
            - larissa_net
        volumes:
            - .:/app
            - media:/app/media

volumes:
  pgdata:
  media:

networks:
  larissa_net: