services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    container_name: db-bot
    restart: always
    environment:
      - POSTGRES_USER=${postgres_user}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_DB=${postgres_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${postgres_usre} -d ${postgres_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - net-bot
  api:
    image: zolppy/aggregator-api:latest
    container_name: api-bot
    environment:
      - BASE_URL_7AZ=${base_url_7az}
      - API_KEY_7AZ=${api_key_7az}
      - DB_URL=${db_url}
      - IXC_HOST=${ixc_host}
      - OPA_TOKEN=${opa_token}
      - OPA_HOST=${opa_host}
      - MIGRATE_DB_URL=${migrate_db_url}
      - IXC_TOKEN=${ixc_token}
      - RUN_MIGRATIONS=1
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - net-bot
    volumes:
      - ./app:/app/app
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
      - media:/app/media
volumes:
  pgdata:
    driver: local
  media:
    driver: local
networks:
  net-bot:
    driver: bridge
