[pytest]
pythonpath = api_roberto
minversion = 7.0
asyncio_mode = auto
addopts = -ra -q --tb=short
testpaths = 
    tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
env_files = 
    .env.test
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning