from pydantic import BaseModel, Field
from typing import List, Optional, Literal


class Meta(BaseModel):
    total: int = Field(ge=1, description="Número total de itens em todas as páginas.")
    page: int = Field(ge=1, description="Número da página atual na sequência de paginação.")
    per_page: int = Field(ge=1, description="Número de itens exibidos por página.")


class Links(BaseModel):
    self: Optional[str] = Field(description="URL da página atual de resultados.")
    next: Optional[str] = Field(description="URL para a próxima página de resultados, se disponível.")
    prev: Optional[str] = Field(description="URL para a página anterior de resultados, se disponível.")


class Contract(BaseModel):
    id_instalador: Optional[int] = Field(None, description="ID do instalador responsável pelo contrato.")
    indicacao_contrato_id: Optional[int] = Field(None, description="ID da indicação associada ao contrato.")
    id_indexador_reajuste: Optional[int] = Field(None, description="ID do indexador usado para reajustes.")
    data_desistencia: Optional[str] = Field(None, description="Data de desistência do contrato.")
    motivo_desistencia: Optional[int] = Field(None, description="Motivo da desistência do contrato.")
    obs_desistencia: Optional[str] = Field(None, description="Observações adicionais sobre a desistência.")
    obs_contrato: Optional[str] = Field(None, description="Observações gerais do contrato.")
    alerta_contrato: Optional[str] = Field(None, description="Alertas associados ao contrato.")
    ids_contratos_recorrencia: Optional[str] = Field(None, description="IDs de contratos de recorrência associados.")
    id_responsavel_desistencia: Optional[int] = Field(None, description="ID do responsável pela desistência.")
    id_responsavel_cancelamento: Optional[int] = Field(None, description="ID do responsável pelo cancelamento.")
    id_responsavel_negativacao: Optional[int] = Field(None, description="ID do responsável pela negativação.")
    origem_cancelamento: Optional[str] = Field(None, description="Origem do cancelamento do contrato.")
    situacao_financeira_contrato: Optional[str] = Field(None, description="Situação financeira atual do contrato.")
    dt_ult_desbloq_auto: Optional[str] = Field(None, description="Data do último desbloqueio automático.")
    dt_ult_desbloq_manual: Optional[str] = Field(None, description="Data do último desbloqueio manual.")
    tempo_permanencia: Optional[str] = Field(None, description="Tempo de permanência do contrato.")
    id: Optional[int] = Field(None, description="ID único do contrato.")
    id_filial: int = Field(..., description="ID da filial associada ao contrato.")
    status: Optional[str] = Field(None, description="Status atual do contrato.")
    status_internet: Optional[str] = Field(None, description="Status do serviço de internet.")
    id_cliente: int = Field(..., description="ID do cliente associado ao contrato.")
    data_assinatura: Optional[str] = Field(None, description="Data de assinatura do contrato.")
    data_ativacao: Optional[str] = Field(None, description="Data de ativação do contrato.")
    data: str = Field(..., description="Data de referência do contrato.")
    data_renovacao: Optional[str] = Field(None, description="Data de renovação do contrato.")
    bloqueio_automatico: str = Field(..., description="Indicador de bloqueio automático.")
    imp_carteira: Optional[str] = Field(None, description="Impressão de carteira do contrato.")
    data_expiracao: Optional[str] = Field(None, description="Data de expiração do contrato.")
    isentar_contrato: Optional[str] = Field(None, description="Indica se o contrato está isento de taxas.")
    pago_ate_data: Optional[str] = Field(None, description="Data até a qual o contrato está pago.")
    id_vd_contrato: int = Field(..., description="ID da venda associada ao contrato.")
    contrato: str = Field(..., description="Número do contrato.")
    endereco: Optional[str] = Field(None, description="Endereço de instalação do serviço.")
    numero: Optional[str] = Field(None, description="Número do endereço de instalação.")
    comissao: Optional[str] = Field(None, description="Valor da comissão do contrato.")
    bairro: Optional[str] = Field(None, description="Bairro do endereço de instalação.")
    tipo: str = Field(..., description="Tipo do contrato.")
    descricao_aux_plano_venda: Optional[str] = Field(None, description="Descrição auxiliar do plano de venda.")
    aviso_atraso: str = Field(..., description="Indicador de aviso por atraso.")
    id_tipo_contrato: int = Field(..., description="ID do tipo de contrato.")
    id_carteira_cobranca: int = Field(..., description="ID da carteira de cobrança.")
    obs: Optional[str] = Field(None, description="Observações gerais.")
    id_modelo: int = Field(..., description="ID do modelo do contrato.")
    status_velocidade: Optional[str] = Field(None, description="Status de velocidade do serviço.")
    id_vendedor: int = Field(..., description="ID do vendedor do contrato.")
    cc_previsao: str = Field(..., description="Centro de custo para previsão.")
    nao_avisar_ate: Optional[str] = Field(None, description="Data até which não enviar avisos.")
    nao_bloquear_ate: Optional[str] = Field(None, description="Data até which não bloquear.")
    id_tipo_documento: int = Field(..., description="ID do tipo de documento.")
    tipo_doc_opc: Optional[int] = Field(None, description="Tipo de documento opcional 1.")
    desconto_fidelidade: Optional[str] = Field(None, description="Valor do desconto por fidelidade.")
    tipo_doc_opc2: Optional[int] = Field(None, description="Tipo de documento opcional 2.")
    tipo_doc_opc3: Optional[int] = Field(None, description="Tipo de documento opcional 3.")
    taxa_improdutiva: Optional[str] = Field(None, description="Valor da taxa improdutiva.")
    tipo_doc_opc4: Optional[int] = Field(None, description="Tipo de documento opcional 4.")
    desbloqueio_confianca: Optional[str] = Field(None, description="Indicador de desbloqueio por confiança.")
    data_negativacao: Optional[str] = Field(None, description="Data de negativação do contrato.")
    data_acesso_desativado: Optional[str] = Field(None, description="Data de desativação do acesso.")
    motivo_cancelamento: Optional[int] = Field(None, description="Motivo do cancelamento do contrato.")
    data_cancelamento: Optional[str] = Field(None, description="Data de cancelamento do contrato.")
    obs_cancelamento: Optional[str] = Field(None, description="Observações do cancelamento.")
    id_vendedor_ativ: Optional[int] = Field(None, description="ID do vendedor na ativação.")
    fidelidade: Optional[str] = Field(None, description="Indicador de fidelidade.")
    tipo_cobranca: str = Field(..., description="Tipo de cobrança do contrato.")
    desbloqueio_confianca_ativo: Optional[str] = Field(None, description="Indicador of desbloqueio por confiança ativo.")
    id_responsavel: Optional[int] = Field(None, description="ID do responsável pelo contrato.")
    taxa_instalacao: Optional[str] = Field(None, description="Valor da taxa de instalação.")
    protocolo_negativacao: Optional[str] = Field(None, description="Protocolo de negativação.")
    dt_ult_bloq_auto: Optional[str] = Field(None, description="Data do último bloqueio automático.")
    dt_ult_bloq_manual: Optional[str] = Field(None, description="Data do último bloqueio manual.")
    dt_ult_des_bloq_conf: Optional[str] = Field(None, description="Data do último desbloqueio por confiança.")
    dt_ult_ativacao: Optional[str] = Field(None, description="Data da última ativação.")
    avalista_1: Optional[int] = Field(None, description="Informações do primeiro avalista.")
    dt_ult_finan_atraso: Optional[str] = Field(None, description="Data da última financeira em atraso.")
    avalista_2: Optional[int] = Field(None, description="Informações do segundo avalista.")
    dt_utl_negativacao: Optional[str] = Field(None, description="Data da última negativação.")
    data_cadastro_sistema: Optional[str] = Field(None, description="Data de cadastro no sistema.")
    ultima_atualizacao: Optional[str] = Field(None, description="Data da última atualização.")
    complemento: Optional[str] = Field(None, description="Complemento do endereço.")
    cep: Optional[str] = Field(None, description="CEP do endereço.")
    imp_importacao: Optional[str] = Field(None, description="Indicador de importação.")
    cidade: Optional[int] = Field(None, description="Cidade do endereço.")
    imp_rede: Optional[str] = Field(None, description="Indicador de rede.")
    renovacao_automatica: str = Field(..., description="Indicador de renovação automática.")
    imp_bkp: Optional[str] = Field(None, description="Indicador de backup.")
    imp_treinamento: Optional[str] = Field(None, description="Indicador de treinamento.")
    motivo_inclusao: Optional[str] = Field(None, description="Motivo da inclusão do contrato.")
    imp_status: Optional[str] = Field(None, description="Status de importação.")
    liberacao_bloqueio_manual: Optional[str] = Field(None, description="Indicador de liberação de bloqueio manual.")
    imp_obs: Optional[str] = Field(None, description="Observações de importação.")
    contrato_suspenso: Optional[str] = Field(None, description="Indicador de contrato suspenso.")
    imp_realizado: Optional[str] = Field(None, description="Indicador de importação realizada.")
    imp_motivo: Optional[str] = Field(None, description="Motivo da importação.")
    imp_inicial: Optional[str] = Field(None, description="Data inicial da importação.")
    imp_final: Optional[str] = Field(None, description="Data final da importação.")
    ativacao_numero_parcelas: Optional[str] = Field(None, description="Número de parcelas na ativação.")
    ativacao_vencimentos: Optional[str] = Field(None, description="Vencimentos das parcelas na ativação.")
    ativacao_valor_parcela: Optional[str] = Field(None, description="Valor da parcela na ativação.")
    id_tipo_doc_ativ: Optional[int] = Field(None, description="ID do tipo de documento na ativação.")
    id_produto_ativ: Optional[int] = Field(None, description="ID do produto na ativação.")
    id_cond_pag_ativ: Optional[int] = Field(None, description="ID da condição de pagamento na ativação.")
    endereco_padrao_cliente: Optional[str] = Field(None, description="Endereço padrão do cliente.")
    referencia: Optional[str] = Field(None, description="Ponto de referência do endereço.")
    id_condominio: Optional[int] = Field(None, description="ID do condomínio.")
    nf_info_adicionais: Optional[str] = Field(None, description="Informações adicionais da NF.")
    assinatura_digital: Optional[str] = Field(None, description="Indicador de assinatura digital.")
    tipo_produtos_plano: Optional[str] = Field(None, description="Tipo de produtos do plano.")
    bloco: Optional[str] = Field(None, description="Bloco do endereço.")
    apartamento: Optional[str] = Field(None, description="Apartamento do endereço.")
    latitude: Optional[str] = Field(None, description="Latitude geográfica.")
    longitude: Optional[str] = Field(None, description="Longitude geográfica.")
    num_parcelas_atraso: Optional[str] = Field(None, description="Número de parcelas em atraso.")
    dt_ult_desiste: Optional[str] = Field(None, description="Data da última desistência.")
    id_contrato_principal: Optional[int] = Field(None, description="ID do contrato principal.")
    gerar_finan_assin_digital_contrato: Optional[str] = Field(None, description="Gerar financeiro com assinatura digital.")
    credit_card_recorrente_token: Optional[str] = Field(None, description="Token do cartão de crédito recorrente.")
    credit_card_recorrente_bandeira_cartao: Optional[str] = Field(None, description="Bandeira do cartão de crédito.")
    id_motivo_negativacao: Optional[int] = Field(None, description="ID do motivo de negativação.")
    obs_negativacao: Optional[str] = Field(None, description="Observações da negativação.")
    restricao_auto_desbloqueio: Optional[str] = Field(None, description="Restrição de desbloqueio automático.")
    motivo_restricao_auto_desbloq: Optional[str] = Field(None, description="Motivo da restrição de desbloqueio automático.")
    nao_susp_parc_ate: Optional[str] = Field(None, description="Data até which não suspender parcelas.")
    liberacao_suspensao_parcial: Optional[str] = Field(None, description="Liberação de suspensão parcial.")
    utilizando_auto_libera_susp_parc: Optional[str] = Field(None, description="Utilizando liberação automática de suspensão parcial.")
    restricao_auto_libera_susp_parcial: Optional[str] = Field(None, description="Restrição de liberação automática de suspensão parcial.")
    motivo_restri_auto_libera_parc: Optional[str] = Field(None, description="Motivo da restrição de liberação automática.")
    data_inicial_suspensao: Optional[str] = Field(None, description="Data inicial de suspensão.")
    data_final_suspensao: Optional[str] = Field(None, description="Data final de suspensão.")
    data_retomada_contrato: Optional[str] = Field(None, description="Data de retomada do contrato.")
    dt_ult_liberacao_susp_parc: Optional[str] = Field(None, description="Data da última liberação de suspensão parcial.")
    base_geracao_tipo_doc: str = Field(..., description="Base para geração do tipo de documento.")
    integracao_assinatura_digital: Optional[str] = Field(None, description="Indicador de integração com assinatura digital.")
    url_assinatura_digital: Optional[str] = Field(None, description="URL da assinatura digital.")
    token_assinatura_digital: Optional[str] = Field(None, description="Token da assinatura digital.")
    testemunha_assinatura_digital: Optional[int] = Field(None, description="Testemunha da assinatura digital.")
    document_photo: Optional[str] = Field(None, description="Foto do documento.")
    selfie_photo: Optional[str] = Field(None, description="Selfie do cliente.")
    tipo_localidade: Optional[str] = Field(None, description="Tipo de localidade.")
    estrato_social_col: Optional[str] = Field(None, description="Estrato social.")
    agrupar_financeiro_contrato: Optional[str] = Field(None, description="Indicador para agrupar financeiro do contrato.")


class StatusContrato(BaseModel):
    status_contrato: Literal["P", "A", "I", "N", "D"]


class StatusContratoOut(BaseModel):
    data: StatusContrato


class ContracListOut(BaseModel):
    data: List[Contract] = Field(..., description="Lista de contratos")
    meta: Meta
    links: Links