from typing import List, Optional, Any
from pydantic import BaseModel, Field


class Contract(BaseModel):
    id_instalador: Optional[Any] = Field(None, description="ID do instalador responsável pelo contrato.")
    indicacao_contrato_id: Optional[Any] = Field(None, description="ID da indicação associada ao contrato.")
    id_indexador_reajuste: Optional[Any] = Field(None, description="ID do indexador usado para reajustes.")
    data_desistencia: Optional[Any] = Field(None, description="Data de desistência do contrato.")
    motivo_desistencia: Optional[Any] = Field(None, description="Motivo da desistência do contrato.")
    obs_desistencia: Optional[Any] = Field(None, description="Observações adicionais sobre a desistência.")
    obs_contrato: Optional[Any] = Field(None, description="Observações gerais do contrato.")
    alerta_contrato: Optional[Any] = Field(None, description="Alertas associados ao contrato.")
    ids_contratos_recorrencia: Optional[Any] = Field(None, description="IDs de contratos de recorrência associados.")
    id_responsavel_desistencia: Optional[Any] = Field(None, description="ID do responsável pela desistência.")
    id_responsavel_cancelamento: Optional[Any] = Field(None, description="ID do responsável pelo cancelamento.")
    id_responsavel_negativacao: Optional[Any] = Field(None, description="ID do responsável pela negativação.")
    origem_cancelamento: Optional[Any] = Field(None, description="Origem do cancelamento do contrato.")
    situacao_financeira_contrato: Optional[Any] = Field(None, description="Situação financeira atual do contrato.")
    dt_ult_desbloq_auto: Optional[Any] = Field(None, description="Data do último desbloqueio automático.")
    dt_ult_desbloq_manual: Optional[Any] = Field(None, description="Data do último desbloqueio manual.")
    tempo_permanencia: Optional[Any] = Field(None, description="Tempo de permanência do contrato.")
    id: Optional[Any] = Field(None, description="ID único do contrato.")
    id_filial: Optional[Any] = Field(None, description="ID da filial associada ao contrato.")
    status: Optional[Any] = Field(None, description="Status atual do contrato.")
    status_internet: Optional[Any] = Field(None, description="Status do serviço de internet.")
    id_cliente: Optional[Any] = Field(None, description="ID do cliente associado ao contrato.")
    data_assinatura: Optional[Any] = Field(None, description="Data de assinatura do contrato.")
    data_ativacao: Optional[Any] = Field(None, description="Data de ativação do contrato.")
    data: Optional[Any] = Field(None, description="Data de referência do contrato.")
    data_renovacao: Optional[Any] = Field(None, description="Data de renovação do contrato.")
    bloqueio_automatico: Optional[Any] = Field(None, description="Indicador de bloqueio automático.")
    imp_carteira: Optional[Any] = Field(None, description="Impressão de carteira do contrato.")
    data_expiracao: Optional[Any] = Field(None, description="Data de expiração do contrato.")
    isentar_contrato: Optional[Any] = Field(None, description="Indica se o contrato está isento de taxas.")
    pago_ate_data: Optional[Any] = Field(None, description="Data até a qual o contrato está pago.")
    id_vd_contrato: Optional[Any] = Field(None, description="ID da venda associada ao contrato.")
    contrato: Optional[Any] = Field(None, description="Número do contrato.")
    endereco: Optional[Any] = Field(None, description="Endereço de instalação do serviço.")
    numero: Optional[Any] = Field(None, description="Número do endereço de instalação.")
    comissao: float = Field(..., description="Valor da comissão do contrato.")
    bairro: Optional[Any] = Field(None, description="Bairro do endereço de instalação.")
    tipo: Optional[Any] = Field(None, description="Tipo do contrato.")
    descricao_aux_plano_venda: Optional[Any] = Field(None, description="Descrição auxiliar do plano de venda.")
    aviso_atraso: Optional[Any] = Field(None, description="Indicador de aviso por atraso.")
    id_tipo_contrato: Optional[Any] = Field(None, description="ID do tipo de contrato.")
    id_carteira_cobranca: Optional[Any] = Field(None, description="ID da carteira de cobrança.")
    obs: Optional[Any] = Field(None, description="Observações gerais.")
    id_modelo: Optional[Any] = Field(None, description="ID do modelo do contrato.")
    status_velocidade: Optional[Any] = Field(None, description="Status de velocidade do serviço.")
    id_vendedor: Optional[Any] = Field(None, description="ID do vendedor do contrato.")
    cc_previsao: Optional[Any] = Field(None, description="Centro de custo para previsão.")
    nao_avisar_ate: Optional[Any] = Field(None, description="Data até which não enviar avisos.")
    nao_bloquear_ate: Optional[Any] = Field(None, description="Data até which não bloquear.")
    id_tipo_documento: Optional[Any] = Field(None, description="ID do tipo de documento.")
    tipo_doc_opc: Optional[Any] = Field(None, description="Tipo de documento opcional 1.")
    desconto_fidelidade: float = Field(..., description="Valor do desconto por fidelidade.")
    tipo_doc_opc2: Optional[Any] = Field(None, description="Tipo de documento opcional 2.")
    tipo_doc_opc3: Optional[Any] = Field(None, description="Tipo de documento opcional 3.")
    taxa_improdutiva: float = Field(..., description="Valor da taxa improdutiva.")
    tipo_doc_opc4: Optional[Any] = Field(None, description="Tipo de documento opcional 4.")
    desbloqueio_confianca: Optional[Any] = Field(None, description="Indicador de desbloqueio por confiança.")
    data_negativacao: Optional[Any] = Field(None, description="Data de negativação do contrato.")
    data_acesso_desativado: Optional[Any] = Field(None, description="Data de desativação do acesso.")
    motivo_cancelamento: Optional[Any] = Field(None, description="Motivo do cancelamento do contrato.")
    data_cancelamento: Optional[Any] = Field(None, description="Data de cancelamento do contrato.")
    obs_cancelamento: Optional[Any] = Field(None, description="Observações do cancelamento.")
    id_vendedor_ativ: Optional[Any] = Field(None, description="ID do vendedor na ativação.")
    fidelidade: Optional[Any] = Field(None, description="Indicador de fidelidade.")
    tipo_cobranca: Optional[Any] = Field(None, description="Tipo de cobrança do contrato.")
    desbloqueio_confianca_ativo: Optional[Any] = Field(None, description="Indicador de desbloqueio por confiança ativo.")
    id_responsavel: Optional[Any] = Field(None, description="ID do responsável pelo contrato.")
    taxa_instalacao: float = Field(..., description="Valor da taxa de instalação.")
    protocolo_negativacao: Optional[Any] = Field(None, description="Protocolo de negativação.")
    dt_ult_bloq_auto: Optional[Any] = Field(None, description="Data do último bloqueio automático.")
    dt_ult_bloq_manual: Optional[Any] = Field(None, description="Data do último bloqueio manual.")
    dt_ult_des_bloq_conf: Optional[Any] = Field(None, description="Data do último desbloqueio por confiança.")
    dt_ult_ativacao: Optional[Any] = Field(None, description="Data da última ativação.")
    avalista_1: Optional[Any] = Field(None, description="Informações do primeiro avalista.")
    dt_ult_finan_atraso: Optional[Any] = Field(None, description="Data da última financeira em atraso.")
    avalista_2: Optional[Any] = Field(None, description="Informações do segundo avalista.")
    dt_utl_negativacao: Optional[Any] = Field(None, description="Data da última negativação.")
    data_cadastro_sistema: Optional[Any] = Field(None, description="Data de cadastro no sistema.")
    ultima_atualizacao: Optional[Any] = Field(None, description="Data da última atualização.")
    complemento: Optional[Any] = Field(None, description="Complemento do endereço.")
    cep: Optional[Any] = Field(None, description="CEP do endereço.")
    imp_importacao: Optional[Any] = Field(None, description="Indicador de importação.")
    cidade: Optional[Any] = Field(None, description="Cidade do endereço.")
    imp_rede: Optional[Any] = Field(None, description="Indicador de rede.")
    renovacao_automatica: Optional[Any] = Field(None, description="Indicador de renovação automática.")
    imp_bkp: Optional[Any] = Field(None, description="Indicador de backup.")
    imp_treinamento: Optional[Any] = Field(None, description="Indicador de treinamento.")
    motivo_inclusao: Optional[Any] = Field(None, description="Motivo da inclusão do contrato.")
    imp_status: Optional[Any] = Field(None, description="Status de importação.")
    liberacao_bloqueio_manual: Optional[Any] = Field(None, description="Indicador de liberação de bloqueio manual.")
    imp_obs: Optional[Any] = Field(None, description="Observações de importação.")
    contrato_suspenso: Optional[Any] = Field(None, description="Indicador de contrato suspenso.")
    imp_realizado: Optional[Any] = Field(None, description="Indicador de importação realizada.")
    imp_motivo: Optional[Any] = Field(None, description="Motivo da importação.")
    imp_inicial: Optional[Any] = Field(None, description="Data inicial da importação.")
    imp_final: Optional[Any] = Field(None, description="Data final da importação.")
    ativacao_numero_parcelas: Optional[Any] = Field(None, description="Número de parcelas na ativação.")
    ativacao_vencimentos: Optional[Any] = Field(None, description="Vencimentos das parcelas na ativação.")
    ativacao_valor_parcela: Optional[Any] = Field(None, description="Valor da parcela na ativação.")
    id_tipo_doc_ativ: Optional[Any] = Field(None, description="ID do tipo de documento na ativação.")
    id_produto_ativ: Optional[Any] = Field(None, description="ID do produto na ativação.")
    id_cond_pag_ativ: Optional[Any] = Field(None, description="ID da condição de pagamento na ativação.")
    endereco_padrao_cliente: Optional[Any] = Field(None, description="Endereço padrão do cliente.")
    referencia: Optional[Any] = Field(None, description="Ponto de referência do endereço.")
    id_condominio: Optional[Any] = Field(None, description="ID do condomínio.")
    nf_info_adicionais: Optional[Any] = Field(None, description="Informações adicionais da NF.")
    assinatura_digital: Optional[Any] = Field(None, description="Indicador de assinatura digital.")
    tipo_produtos_plano: Optional[Any] = Field(None, description="Tipo de produtos do plano.")
    bloco: Optional[Any] = Field(None, description="Bloco do endereço.")
    apartamento: Optional[Any] = Field(None, description="Apartamento do endereço.")
    latitude: Optional[Any] = Field(None, description="Latitude geográfica.")
    longitude: Optional[Any] = Field(None, description="Longitude geográfica.")
    num_parcelas_atraso: Optional[Any] = Field(None, description="Número de parcelas em atraso.")
    dt_ult_desiste: Optional[Any] = Field(None, description="Data da última desistência.")
    id_contrato_principal: Optional[Any] = Field(None, description="ID do contrato principal.")
    gerar_finan_assin_digital_contrato: Optional[Any] = Field(None, description="Gerar financeiro com assinatura digital.")
    credit_card_recorrente_token: Optional[Any] = Field(None, description="Token do cartão de crédito recorrente.")
    credit_card_recorrente_bandeira_cartao: Optional[Any] = Field(None, description="Bandeira do cartão de crédito.")
    id_motivo_negativacao: Optional[Any] = Field(None, description="ID do motivo de negativação.")
    obs_negativacao: Optional[Any] = Field(None, description="Observações da negativação.")
    restricao_auto_desbloqueio: Optional[Any] = Field(None, description="Restrição de desbloqueio automático.")
    motivo_restricao_auto_desbloq: Optional[Any] = Field(None, description="Motivo da restrição de desbloqueio automático.")
    nao_susp_parc_ate: Optional[Any] = Field(None, description="Data até which não suspender parcelas.")
    liberacao_suspensao_parcial: Optional[Any] = Field(None, description="Liberação de suspensão parcial.")
    utilizando_auto_libera_susp_parc: Optional[Any] = Field(None, description="Utilizando liberação automática de suspensão parcial.")
    restricao_auto_libera_susp_parcial: Optional[Any] = Field(None, description="Restrição de liberação automática de suspensão parcial.")
    motivo_restri_auto_libera_parc: Optional[Any] = Field(None, description="Motivo da restrição de liberação automática.")
    data_inicial_suspensao: Optional[Any] = Field(None, description="Data inicial de suspensão.")
    data_final_suspensao: Optional[Any] = Field(None, description="Data final de suspensão.")
    data_retomada_contrato: Optional[Any] = Field(None, description="Data de retomada do contrato.")
    dt_ult_liberacao_susp_parc: Optional[Any] = Field(None, description="Data da última liberação de suspensão parcial.")
    base_geracao_tipo_doc: Optional[Any] = Field(None, description="Base para geração do tipo de documento.")
    integracao_assinatura_digital: Optional[Any] = Field(None, description="Indicador de integração com assinatura digital.")
    url_assinatura_digital: Optional[Any] = Field(None, description="URL da assinatura digital.")
    token_assinatura_digital: Optional[Any] = Field(None, description="Token da assinatura digital.")
    testemunha_assinatura_digital: Optional[Any] = Field(None, description="Testemunha da assinatura digital.")
    document_photo: Optional[Any] = Field(None, description="Foto do documento.")
    selfie_photo: Optional[Any] = Field(None, description="Selfie do cliente.")
    tipo_localidade: Optional[Any] = Field(None, description="Tipo de localidade.")
    estrato_social_col: Optional[Any] = Field(None, description="Estrato social.")
    agrupar_financeiro_contrato: Optional[Any] = Field(None, description="Indicador para agrupar financeiro do contrato.")


class ContracListOut(BaseModel):
    data: List[Contract] = Field(..., description="Lista de contratos")