from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = "1ff3a211b47f"
down_revision: Union[str, Sequence[str], None] = "bbb5f03fe570"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Adicionar novas colunas
    op.add_column("logs", sa.Column("data", sa.Date(), nullable=True))
    op.add_column("logs", sa.Column("hora", sa.Time(), nullable=True))

    # 2. Preencher as novas colunas com dados da coluna datetime existente
    connection = op.get_bind()
    results = connection.execute(sa.text("SELECT id, datetime FROM logs"))

    for row in results:
        connection.execute(
            sa.text("UPDATE logs SET data = :data, hora = :hora WHERE id = :id"),
            {
                "data": row.datetime.date() if row.datetime else None,
                "hora": row.datetime.time() if row.datetime else None,
                "id": row.id,
            },
        )

    # 3. Tornar as novas colunas NOT NULL (após preenchimento)
    op.alter_column("logs", "data", nullable=False)
    op.alter_column("logs", "hora", nullable=False)

    # 4. Remover a coluna datetime original (opcional)
    op.drop_column("logs", "datetime")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Adicionar coluna datetime de volta
    op.add_column("logs", sa.Column("datetime", postgresql.TIMESTAMP(), nullable=True))

    # 2. Preencher datetime combinando data e hora
    connection = op.get_bind()
    results = connection.execute(sa.text("SELECT id, data, hora FROM logs"))

    for row in results:
        if row.data and row.hora:
            datetime_combined = sa.func.make_timestamp(
                row.data.year,
                row.data.month,
                row.data.day,
                row.hora.hour,
                row.hora.minute,
                row.hora.second,
            )
            connection.execute(
                sa.text("UPDATE logs SET datetime = :datetime WHERE id = :id"),
                {"datetime": datetime_combined, "id": row.id},
            )

    # 3. Tornar datetime NOT NULL
    op.alter_column("logs", "datetime", nullable=False)

    # 4. Remover as colunas data e hora
    op.drop_column("logs", "hora")
    op.drop_column("logs", "data")

    # ### end Alembic commands ###
