"""adicionada nova coluna na tabela, coluna 'protocolo'

Revision ID: ed6f3b30a943
Revises: e8dcca57086b
Create Date: 2025-11-10 20:10:22.192570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6f3b30a943'
down_revision: Union[str, Sequence[str], None] = 'e8dcca57086b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
